### PR TITLE
3.3.5 vas autobalance

### PR DESCRIPTION
**Pull request by acidmanifesto**
Description:

Vas Autobalance 30m Option added

Current behavior:
per prior conversation in discord and suggestion. 30m option added
https://github.com/TrinityCore/TrinityCoreCustomChanges/issues/22

Branch(es):

3.3.5

TC rev. hash/commit:

Parent: 1ff4a7e (DB/Quest: Fix CompletionText of 'The Balance of Nature')
Branch: 3.3.5
Follows: TDB335.64

### CODE REVIEW

**Comment by Aokromes** [comment]
it lacks the hack to allow to enter more than 10 persons on a 10m raid xd

**Comment by acidmanifesto** [comment]
Ah ok. I will look at it later today then.

**Comment by acidmanifesto** [comment]
> it lacks the hack to allow to enter more than 10 persons on a 10m raid xd

alrighty. all tests passed travis ci. Hopefully i got it right with in your specifications.

**Comment by acidmanifesto** [comment]
> it lacks the hack to allow to enter more than 10 persons on a 10m raid xd

Is it suitable now? @Aokromes

**Comment by jackpoz** [comment]
@acidmanifesto after this PR gets merged, you should delete your local branch and create it from the one in this repo as we squashed the commits (that's why this PR shows 26 commits when you actually just added only a few).

Is this ready to be merged or ?

**Comment by acidmanifesto** [comment]
@jackpoz it is ready and will do. Not certain if i have direct push access if i delete the local but it wouldnt be hard to start a new local branch for PR if need be.

**Pull request merged**
