### PR TITLE
chore (passive_anticheat): clean up and build fix

### PR DESCRIPTION
**Pull request by acidmanifesto**
**Changes proposed**:

- White Space Fix thanks to @Aokromes for identifying
- .c_str() to fix debian build
- add logging to auto jail and jail command as a form of spacer before casting spells after teleporting.

**Target branch(es)**: 335-passive_anticheat

**Issues addressed**: Fixes # https://github.com/TrinityCore/TrinityCoreCustomChanges/issues/132
Possible Fix # https://github.com/TrinityCore/TrinityCoreCustomChanges/issues/124

**Tests performed**: (Does it build, tested in-game, etc)

**Known issues and TODO list**:

- [ ] 
- [ ]

### CODE REVIEW

**Comment by acidmanifesto** [comment]
if possible. Are you able to test and report any compile issues @DykeRz or @Aokromes 
Also can you confirm if the crash is happening on your end @CraftedRO

**Comment by Aokromes** [comment]
[100%] Built target worldserver

real    13m14.884s
user    46m31.323s
sys     1m47.208s

it builds on debian 11.

**Comment by CraftedRO** [comment]
Crash still occured.

**Comment by acidmanifesto** [comment]
> Crash still occured.

do you have a crash log you can provide using this pr? at this point i can't seem to replicate any crashing further, maybe the log can provide further information i am not seeing to see what the difference is between your end and mines.

**Comment by acidmanifesto** [comment]
> Crash still occured.

I went ahead and did a load order change up. can you test again at your earlier convince please?

**Comment by CraftedRO** [comment]
the crashlong was attached to the issue, for earlier question.

**Comment by CraftedRO** [comment]
the new crashlog was attached to the issue, for earlier question.
I will test changes again soon.

**Comment by CraftedRO** [comment]
Tested again, [still crash](https://github.com/TrinityCore/TrinityCoreCustomChanges/issues/124#issuecomment-1954415538), sorry.

**Comment by acidmanifesto** [comment]
closing for now. will reopen for build fix debian 11 only. will investigate the crash in a seperate pr.

**Pull request closed without merging**
