### PR TITLE
Death Knight Skip Module

### PR DESCRIPTION
**Pull request by acidmanifesto**
Skip Death Knight Module

**SHORT DESCRIPTION:
Adjustable Module to skip the Death Knight Starter Quest Zone on new player creation so a player can go straight in to adventuring with all appropiate gear, items, and skills.**

Original Module From Single Player Project Consolidated Skip Module
Rewritten for TC 335 By Single Player Project Developer MDic
Original Concept from conanhun513
Works for both horde and alliance new characters.
When Module is active (Conf = 1) and then a new character Death Knight is created, intro is played (not skippable). Character is then given flags and triggers based on quest completions for the starter areas and give the initial turn in quest after leaving the ebon hold. Alliance DK will be in storm wind with the quest https://www.wowhead.com/quest=13188/where-kings-walk ready for turn in, and Horde DK will be in Orgrimmar with the quest https://www.wowhead.com/quest=13189/saurfangs-blessing. All obtainable key Character Items are in the player's inventory or auto equipped, (Tabard, Weapons, Armors, and such). Spells such as Death Gate works and does return you to the appropriate ebon hold after the DK start zone chain quests are finished.
Runeforging, journeyman riding skill and deathcharge mount is learned as well.
Tested and working on current 335 with all items and quests and triggers researched for 335 branch.
Original Module is based on our V2 Legion Project consolidate skip module.

Co-Authored-By: ConanHUN <conan_513@hotmail.com>
Co-Authored-By: Serithul <62258982+serithul@users.noreply.github.com>
Co-Authored-By: Warlord Zul'Jin <42502821+takasi689@users.noreply.github.com>

https://github.com/TrinityCore/TrinityCoreCustomChanges/issues/36

### CODE REVIEW

**Comment by acidmanifesto** [comment]
@Aokromes 
If requested I can offer the following for this module as well:
1) Customizable Start level for for if using the DK Skip module for server operators to chose what the adjusted make up level will be for skipping the zone. (Currently default is Level 58)
2) Make a separate Conf Option for GM only accounts to use the Skip Module, and not normal players.

**Comment by acidmanifesto** [comment]
All Checks Passed. @Aokromes 
Preview Video: https://youtu.be/yBOx85LWly8

**Comment by Aokromes** [comment]
yeah add the 2 confs.

**Comment by acidmanifesto** [comment]
@Aokromes all good to go

**Comment by jackpoz** [comment]
squashed and merged.
I would suggest to recreate your local and remote branch from the squashed and merged one.
thanks for the PR.

**Pull request merged**
