### PR TITLE
Prevent excess loot mail when item never usable or is unique.

### PR DESCRIPTION
**Pull request by andrew-wroe**
**Changes proposed**:

I found that excess loot would send multiple unique items as mail.
It became quite annoying to delete these later on from the mailbox.
This change skips over sending of both unique and unusable items.

**Target branch(es)**: 335/6x

**Issues addressed**: Fixes #
Since it's not strictly a bug (more an improvement in behaviour), I've not raised a ticket for this but will do so if required.

**Tests performed**: I've built this locally and run for some days.

**Known issues and TODO list**: None

### CODE REVIEW

**Comment by qyh214** [comment]
If you refer to Blizzard specifications, that's blizzlike!

The existing script performance is correct. I suggest this as an option. 

----

I think there is a more needed function. At present, each booty occupies one email. In fact, I think if it is in a short time, it should be placed in one email for quick retrieval, rather than spam the whole mailbox

**Comment by Juggalo187** [comment]
Try this in loothandler.cpp it should prevent items that can't/shouldn't be looted from being mailed. So you don't end up getting emails of quest starting items and other "unique" items that can't be looted.

```
 if (LootItem* item = loot->LootItemInSlot(i, player))
                    {
						ItemPosCountVec dest;
						InventoryResult msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, item->itemid, item->count);

                        if (player->AddItem(item->itemid, item->count))
                        {
                            player->SendNotifyLootItemRemoved(lootSlot);
                            player->SendLootRelease(player->GetLootGUID());
                        }
                        else
                        {
							if (msg != EQUIP_ERR_CANT_CARRY_MORE_OF_THIS)
							{
								player->SendItemRetrievalMail(item->itemid, item->count);
								player->SendNotifyLootItemRemoved(lootSlot);
								player->SendLootRelease(player->GetLootGUID());
								player->GetSession()->SendAreaTriggerMessage("Your items has been mailed to you.");
							}
                        }
					}
```

The key parts are 

`InventoryResult msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, item->itemid, item->count);`

and

`if (msg != EQUIP_ERR_CANT_CARRY_MORE_OF_THIS)`

**Comment by andrew-wroe** [comment]
@qyh214 - to be honest I'm not sure on what counts as blizzlike here. I thought this whole branch was providing a non-blizzlike feature (at least so far as WotLK is concerned). Still I see no harm in making it a configurable option under AOE.LOOT so I'll look into that. In fact maybe the excess loot mailing should be separately configurable, but that's more a choice for the original author.

@Juggalo187 - I can see how using the result of CanStoreNewItem will avoid this, but that's also called by AddItem so it seems inefficient to force yet another call when the latter function can be adapted to optionally return the result. Also, I think we need to filter out EQUIP_ERR_YOU_CAN_NEVER_USE_THAT_ITEM as well, but since I'm going to make it configurable that can be something left to runtime.

**Comment by Juggalo187** [comment]
@andrew-wroe Ok yeah I don't know C+ or anything so I was trying to stop unique items like Mangled journal from filling the mailbox and that seemed to do it. Your way probably is way better
 
It seems like a bug to me, I can't imagine why someone would want 100 quest starting items like "A Mangled Journal" mailed to their mailbox. Those Unique items mailed to the mailbox can't even be removed anyway since you already have one of them right so by default shouldn't they just not be mailed? 

Maybe Unique or Unique-Equipped items that are BOE because people could move/sell the item so they can take another out of the mailbox but I assume the vast majority of those items are BOP.

**Comment by acidmanifesto** [comment]
@andrew-wroe so sorry. i been busy irl recently and just now got some time to review the issues. If you are able to make a additional conf to enable the filtering separately such as a new if statement in the loothandler, then i am certain there will be zero arguements with how this modification can be handled in full and I will be willing to give full blessing on the PR personally to the tc devs.

**Pull request closed without merging**
